version: '3'
services:
  go:
    build:
      context: ./
      dockerfile: ./Dockerfile_go
    volumes:
      - .:/go/src/github.com/homma509/9hash/:cached
    depends_on: 
      - dynamodb
    security_opt:
      - seccomp:unconfined
    env_file: 
      - .env.development
      - .env.dynamodb-local
    networks:
      - net

  sls:
    build:
      context: ./
      dockerfile: ./Dockerfile_sls
    volumes: 
      - .:/opt/app
    env_file: 
      - .env.aws-credentials
    networks:
      - net
    # tty:
    #   true

  dynamodb:
    build:
      context: ./
      dockerfile: ./Dockerfile_dynamodb
    ports: 
      - '8000:8000'
    volumes: 
      - .:/var/opt
    env_file: 
      - .env.dynamodb-local
    networks:
      - net

  npm:
    build:
      context: ./web/
      dockerfile: ./Dockerfile_npm
    ports: 
      - "8080:8080"
    volumes: 
      - ./web/app:/usr/src/app/
    env_file: 
      - ./web/app/.env
    networks:
      - net
    # tty:
    #   true

networks:
  net:
    driver: bridge